server:
  port: 8002

spring:
  application:
    name: bonuspoint-config-server
  cloud:
    config:
      server:
        git:
          # git仓库位置
          uri: https://dev.33.cn/wangtao/bonus-point-cloud.git
          # 仓库路径下的相对搜索位置
          search-paths: bonuspoint-config-repo
          # git仓库的用户名
          username: wangtao
          # git仓库的用户密码
          password: wang5341.

  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 是否优先使用IP地址作为主机名的标识，默认为false
    prefer-ip-address: true
    # 客户端向服务端发送心跳（服务续约任务）的调用时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳之后的等待时间上限（服务时效的时间），默认为90秒
    lease-expiration-duration-in-seconds: 90
  client:
    # 服务注册中心地址，多个地址用 , 隔开
    service-url:
      defaultZone: http://admin:123456@${eureka.host:123.207.85.155}:${eureka.port:1111}/eureka/


