server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      # 认证使用的用户名
      name: admin
      # 认证使用的密码
      password: 123456
  cloud:
    config:
      server:
        git:
          # git仓库位置
          uri: https://github.com/qbanxiaoli/sms-cloud-config.git
          # 仓库路径下的相对搜索位置
          search-paths: /**
          # git仓库的用户名
#          username:
          # git仓库的用户密码
#          password:

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address:${spring.cloud.client.ip-address}}:${server.port}
    # 是否优先使用IP地址作为主机名的标识，默认为false
    prefer-ip-address: true
    # 客户端向服务端发送心跳（服务续约任务）的调用时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳之后的等待时间上限（服务时效的时间），默认为90秒
    lease-expiration-duration-in-seconds: 90
  client:
    # 服务注册中心地址,多个地址用,隔开
    service-url:
      defaultZone: http://admin:123456@${eureka.host:localhost}:${eureka.port:1111}/eureka/


