version: '3.0'
services:
  # 注册中心
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/qbanxiaoli/eureka
    restart: always
    tty: true
    container_name: eureka
    ports:
    - "1111:1111"
  # 配置中心
  config:
    image: registry.cn-hangzhou.aliyuncs.com/qbanxiaoli/config
    restart: always
    tty: true
    container_name: config
    ports:
    - "8888:8888"
    depends_on:
    - eureka
  # 短信服务
  tool:
    image: registry.cn-hangzhou.aliyuncs.com/qbanxiaoli/tool
    restart: always
    tty: true
    container_name: tool
    ports:
    - "8001:8001"
    depends_on:
    - eureka
    - config
    volumes:
    - ${HOME}/sms/logs/sms:/logs/tool
  # 网关
  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/qbanxiaoli/gateway
    restart: always
    tty: true
    container_name: gateway
    ports:
    - "8000:8000"
    depends_on:
    - eureka
    - config


