version: '3.0'
services:
  # 注册中心
  eureka:
    image: eureka
    restart: always
    tty: true
    container_name: eureka
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=192.168.21.61
    ports:
    - "1111:1111"
  # 配置中心
  config:
    image: config
    restart: always
    tty: true
    container_name: config
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=192.168.21.61
    - EUREKA_HOST=192.168.21.61
    - JASYPT_PASSWORD=tool
    ports:
    - "8888:8888"
  # 工具服务
  tool:
    image: tool
    restart: always
    tty: true
    container_name: tool
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=192.168.21.61
    - EUREKA_HOST=192.168.21.61
    - JASYPT_PASSWORD=tool
    ports:
    - "8001:8001"
    volumes:
    - ${HOME}/tool/logs:${HOME}/logs
  # 网关
  gateway:
    image: gateway
    restart: always
    tty: true
    container_name: gateway
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=192.168.21.61
    - EUREKA_HOST=192.168.21.61
    - JASYPT_PASSWORD=tool
    ports:
    - "8000:8000"


