version: '3.0'
services:
  # 注册中心
  eureka:
    image: qbanxiaoli/eureka
    restart: always
    tty: true
    container_name: eureka
    ports:
      - "1111:1111"
  # 配置中心
  config:
    image: qbanxiaoli/config
    restart: always
    tty: true
    container_name: config
    ports:
      - "8888:8888"
  # 短信服务
  sms:
    image: qbanxiaoli/sms
    restart: always
    tty: true
    container_name: sms
    ports:
      - "8001:8001"
  # 网关
  zuul:
    image: qbanxiaoli/zuul
    restart: always
    tty: true
    container_name: zuul
    ports:
      - "8000:8000"


