version: '3.0'
services:
  # 注册中心
  eureka:
    image: eureka
    restart: always
    tty: true
    container_name: eureka
    ports:
    - "1111:1111"
  # 配置中心
  config:
    image: config
    restart: always
    tty: true
    container_name: config
    environment:
    - JASYPT_PASSWORD=tool
    ports:
    - "8888:8888"
    depends_on:
    - eureka
  # 工具服务
  tool:
    image: tool
    restart: always
    tty: true
    container_name: tool
    environment:
    - JASYPT_PASSWORD=tool
    ports:
    - "8001:8001"
    depends_on:
    - eureka
    - config
    volumes:
    - ${HOME}/sms/logs/sms:/logs/tool
  # 网关
  gateway:
    image: gateway
    restart: always
    tty: true
    container_name: gateway
    environment:
    - JASYPT_PASSWORD=tool
    ports:
    - "8000:8000"
    depends_on:
    - eureka
    - config


